// File generated by FlutterFire CLI.
// ignore_for_file: type=lint


import 'package:firebase_core/firebase_core.dart';
import 'package:flutter/foundation.dart';
import 'package:flutter/material.dart';

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAxh56Pz2RK6CHy2m7Ro0ni7YcXpgfsIEw',
    appId: '1:1085226622635:android:d6db31d18f5c58cf6021ee',
    messagingSenderId: '1085226622635',
    projectId: 'apace-6eccc',
    storageBucket: 'apace-6eccc.appspot.com',
  );

//

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDfKNw2qQaGfhp0qlVB42hvZJjc7XktPPw',
    appId: '1:1085226622635:ios:28c1d177715543856021ee',
    messagingSenderId: '1085226622635',
    projectId: 'apace-6eccc',
    storageBucket: 'apace-6eccc.appspot.com',
    androidClientId: '1085226622635-0n98325hcr8f45d8jusuocidhcdnjb22.apps.googleusercontent.com',
    iosBundleId: 'com.example.mytester',
  );


 }