name: Android Fastlane with Firebase App Distribution Workflow

on:
  push:
    branches:
      - master

jobs:
  distribute_to_firebase:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout my repo code
        uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'temurin'

      - name: Install Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: "3.3.5"
          bundler-cache: true
        # Removed working-directory here because Ruby setup applies globally

      - name: Install Fastlane and dependencies
        run: |
          bundle install
        # Removed working-directory because the Fastlane Gemfile might be in the root

      - name: Build and Distribute App
        env:
          FIREBASE_CLI_TOKEN: ${{ secrets.FIREBASE_CLI_TOKEN }} # Ensure you have this secret added in your GitHub settings
        run: |
          flutter clean
          flutter pub get
          bundle exec fastlane firebase_distribution
        # Removed working-directory if the Fastfile and android folder is in the root of the project
